
import React from 'react';
import { getFormContent } from '@/lib/actions/dras-actions';
import { ChevronLeft, Printer, FileEdit, Share2, Download, Info } from 'lucide-react';
import Link from 'next/link';

export default async function FormViewerPage({ params }: { params: Promise<{ appendixId: string, formId: string }> }) {
  const { appendixId, formId } = await params;
  const result = await getFormContent(appendixId, formId);

  if (!result.success) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-red-400">
        <h2 className="text-2xl font-bold">Ошибка загрузки формы</h2>
        <p className="text-slate-500 mt-2">{result.error}</p>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto">
      {/* Header Actions */}
      <div className="flex items-center justify-between mb-8">
        <Link 
          href="/navigator"
          className="flex items-center gap-2 text-slate-400 hover:text-cyan-400 transition-colors text-sm font-medium"
        >
          <ChevronLeft size={16} /> Назад к списку
        </Link>
        <div className="flex items-center gap-3">
          <button className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-sm font-semibold hover:bg-white/10 transition-all active:scale-95">
            <Printer size={16} /> Печать
          </button>
          <Link href={`/digital-forms/${formId}`}>
            <button className="flex items-center gap-2 px-4 py-2 bg-cyan-500 text-black rounded-xl text-sm font-bold hover:bg-cyan-400 transition-all shadow-lg shadow-cyan-500/20 active:scale-95">
              <FileEdit size={16} /> Оцифровать
            </button>
          </Link>
          <div className="w-px h-6 bg-white/10 mx-2" />
          <button className="p-2 text-slate-500 hover:text-white transition-colors">
            <Download size={18} />
          </button>
          <button className="p-2 text-slate-500 hover:text-white transition-colors">
            <Share2 size={18} />
          </button>
        </div>
      </div>

      {/* Main Form Content */}
      <div className="bg-white/[0.02] border border-white/10 rounded-3xl overflow-hidden backdrop-blur-md">
        {/* Form Info Bar */}
        <div className="p-6 border-b border-white/10 bg-white/5 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-cyan-500/20 flex items-center justify-center border border-cyan-500/30">
              <FileEdit size={24} className="text-cyan-400" />
            </div>
            <div>
              <h1 className="text-xl font-bold">{formId.replace('_', ' ')}</h1>
              <p className="text-xs text-slate-500 uppercase tracking-widest">{appendixId.replace('_', ' ')} • ПРИКАЗ №260</p>
            </div>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-orange-500/10 border border-orange-500/20 text-orange-400 text-xs font-bold">
            <Info size={12} /> ТРЕБУЕТСЯ ОЦИФРОВКА
          </div>
        </div>

        {/* Markdown Rendering Area */}
        <div className="p-12 prose prose-invert prose-cyan max-w-none">
          <pre className="whitespace-pre-wrap font-mono text-xs leading-relaxed text-slate-300 bg-transparent p-0 border-0">
            {result.content}
          </pre>
        </div>
        
        {/* Footer info */}
        <div className="p-8 border-t border-white/5 bg-black/20 text-[10px] text-slate-600 font-mono flex justify-between italic">
          <span>SOURCE: {result.path}</span>
          <span>AUTOGENERATED BY DRAS-260 ENGINE</span>
        </div>
      </div>
    </div>
  );
}
